In [43]:
!pip install pymongo pandas scikit-learn

Requirement already satisfied: pymongo in /usr/local/lib/python3.12/dist-packages (4.16.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo) (2.8.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [44]:
import pandas as pd
import numpy as np
from pymongo import MongoClient
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [45]:
from pymongo import MongoClient

MONGO_URI = "mongodb+srv://admin:colabmind2026@colabmind.ueixusq.mongodb.net/?appName=ColabMind"

client = MongoClient(MONGO_URI)

db = client["instagram_db"]
collection = db["profiles"]

print("Connected to MongoDB")

Connected to MongoDB

In [46]:
import pandas as pd

data = list(collection.find({}))

rows = []

for doc in data:

    profile = doc.get("profile", {})

    rows.append({

        "followers": profile.get("follower_count", 0),
        "following": profile.get("following_count", 0),
        "posts": profile.get("post_count", 0),

        "engagement_rate": profile.get("engagement_rate", 0),
        "engagement_percent": profile.get("engagement_%", 0),

        "avg_likes": profile.get("like_count_avg", 0),
        "avg_comments": profile.get("comment_count_avg", 0),

        "posting_frequency": profile.get("posting_frequency_weekly", 0),

        "video_ratio": profile.get("video_ratio", 0),
        "image_ratio": profile.get("image_ratio", 0)

    })

df = pd.DataFrame(rows)

df.head()

,followers,following,posts,engagement_rate,engagement_percent,avg_likes,avg_comments,posting_frequency,video_ratio,image_ratio
0,511839670,356,1464,0.013133,1.3133,6597873.17,123908.50,84.0,0.250,0.750
1,672022038,629,4018,0.006121,0.6121,4057797.33,55799.50,84.0,0.167,0.833
2,391111920,131,7374,0.003587,0.3587,1398463.33,4402.75,84.0,0.250,0.750
3,390622552,308,8306,0.001370,0.1370,531351.83,3739.58,84.0,0.750,0.250
4,275045742,286,1047,0.031982,3.1982,8651686.75,144822.83,84.0,0.500,0.500

In [47]:
def risk_label(row):

    engagement = row["engagement_percent"]
    followers = row["followers"]
    likes = row["avg_likes"]

    if engagement > 3 and likes > followers * 0.02:
        return "Low Risk"

    elif engagement > 1:
        return "Medium Risk"

    else:
        return "High Risk"


df["risk"] = df.apply(risk_label, axis=1)

df["risk"].value_counts()

risk
High Risk      61
Low Risk       40
Medium Risk    25
Name: count, dtype: int64

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

X = df.drop("risk", axis=1)
y = df["risk"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

pred = model.predict(X_test)

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

   High Risk       1.00      1.00      1.00        14
    Low Risk       1.00      1.00      1.00         9
 Medium Risk       1.00      1.00      1.00         3

    accuracy                           1.00        26
   macro avg       1.00      1.00      1.00        26
weighted avg       1.00      1.00      1.00        26

In [49]:
def predict_risk(username):

    doc = collection.find_one({"profile.username": username})

    if not doc:
        return {"error": "Username not found"}

    p = doc["profile"]

    data = {

        "followers": p.get("follower_count", 0),
        "following": p.get("following_count", 0),
        "posts": p.get("post_count", 0),

        "engagement_rate": p.get("engagement_rate", 0),
        "engagement_percent": p.get("engagement_%", 0),

        "avg_likes": p.get("like_count_avg", 0),
        "avg_comments": p.get("comment_count_avg", 0),

        "posting_frequency": p.get("posting_frequency_weekly", 0),

        "video_ratio": p.get("video_ratio", 0),
        "image_ratio": p.get("image_ratio", 0)
    }

    df_input = pd.DataFrame([data])

    risk = model.predict(df_input)[0]

    return {
        "username": username,
        "collaboration_risk": risk
    }

In [50]:
predict_risk("leomessi")

{'username': 'leomessi', 'collaboration_risk': 'Medium Risk'}

In [51]:
import requests

API_KEY = "fyiSyz3m7jrv8KUHYPR78bcb"

def scrape_profile(username):

    url = "https://www.searchapi.io/api/v1/search"

    params = {
        "engine": "instagram_profile",
        "username": username,
        "api_key": API_KEY
    }

    response = requests.get(url, params=params)

    if response.status_code != 200:
        print(f"API failed for {username}: {response.status_code} - {response.text}")
        return False

    data = response.json()

    profile = data.get("profile", {})

    # Get engagement_rate from API response
    api_engagement_rate = profile.get("engagement_rate", 0)

    profile_data = {
        "profile":{
            "username": username,
            "follower_count": profile.get("followers", 0),
            "following_count": profile.get("following", 0),
            "post_count": profile.get("posts", 0),
            "engagement_rate": api_engagement_rate, # Store the raw engagement rate
            "engagement_%": api_engagement_rate * 100, # Store as percentage
            "like_count_avg": profile.get("avg_likes", 0),
            "comment_count_avg": profile.get("avg_comments", 0),
            "posting_frequency_weekly": 0, # Not provided by SearchAPI, default to 0
            "video_ratio": 0,              # Not provided by SearchAPI, default to 0
            "image_ratio": 0               # Not provided by SearchAPI, default to 0
        }
    }

    collection.insert_one(profile_data)

    print(f"Profile for {username} scraped and saved")

    return True

In [52]:
def predict_collaboration_risk(username):

    # Step 1 → check MongoDB
    doc = collection.find_one({"profile.username": username})

    if not doc:
        print(f"Username {username} not found → scraping")
        scraped = scrape_profile(username)

        if not scraped:
            return {"error": f"Profile for {username} could not be scraped"}

        # Fetch the newly scraped document
        doc = collection.find_one({"profile.username": username})

    # Step 2 → extract features
    p = doc["profile"]

    # Create a dictionary with all 10 features, matching the DataFrame columns used for training
    features_dict = {
        "followers": p.get("follower_count", 0),
        "following": p.get("following_count", 0),
        "posts": p.get("post_count", 0),
        "engagement_rate": p.get("engagement_rate", 0),
        "engagement_percent": p.get("engagement_%", 0),
        "avg_likes": p.get("like_count_avg", 0),
        "avg_comments": p.get("comment_count_avg", 0),
        "posting_frequency": p.get("posting_frequency_weekly", 0),
        "video_ratio": p.get("video_ratio", 0),
        "image_ratio": p.get("image_ratio", 0)
    }

    # Create a DataFrame from the dictionary, ensuring column names match training data
    df_input = pd.DataFrame([features_dict])

    risk = model.predict(df_input)[0]

    return {
        "username": username,
        "collaboration_risk": risk
    }

In [53]:
predict_collaboration_risk("dktestei")

{'username': 'dktestei', 'collaboration_risk': 'High Risk'}

In [54]:
!pip install joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)

In [55]:
import joblib

In [56]:
from sklearn.ensemble import RandomForestClassifier

X = df[["followers","following","posts","engagement_percent","avg_likes","avg_comments"]]
y = df["risk"]

model = RandomForestClassifier(n_estimators=200)

model.fit(X,y)

print("Model trained")

Model trained

In [57]:
joblib.dump(model, "Risk_Prediction_model.joblib")

print("Model saved successfully")

Model saved successfully